# Generated by Django 4.1.4 on 2022-12-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Samochody', '0002_marka_samochody_marka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Modele',
            },
        ),
        migrations.AddField(
            model_name='Samochody',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Samochody.model'),
        ),
    ]
