# Generated by Django 4.1.4 on 2022-12-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Samochody', '0003_model_samochody_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='marka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Samochody.marka'),
        ),
    ]
