# Generated by Django 4.1.4 on 2022-12-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Samochody', '0004_model_marka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Samochody',
            name='nazwa',
            field=models.CharField(max_length=50),
        ),
    ]
